if(PROJECT_IS_TOP_LEVEL AND CMAKE_CXX_CLANG_TIDY)
    option(USE_CTCACHE "Use clang-tidy-cache to speed up static analysis" ON)
    if(USE_CTCACHE)
        find_program(CLANG_TIDY_CACHE_PATH NAMES "clang-tidy-cache")
        if(CLANG_TIDY_CACHE_PATH)
            message("Found clang-tidy-cache")
            message("clang-tidy-cache directory: $ENV{CTCACHE_DIR}")
            set(clang_tidy_path "${CLANG_TIDY_CACHE_PATH};${CMAKE_CXX_CLANG_TIDY}")
            set(CMAKE_CXX_CLANG_TIDY "${clang_tidy_path}")
        else()
            message(WARNING "clang-tidy-cache not found in path")
        endif()
    endif()
endif()
